<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Reference Type' => 'Art der Publikation',
    'Journal article' => 'Journal-Artikel',
    'Book' => 'Buch',
    'Book section' => 'Buchkapitel',
    'Edited book' => 'Buch mit Herausgeber',



    'Author' => 'Autor(en)',
    'Year' => 'Erscheinungsjahr',
    'Title' => 'Titel',
    'Journal' => 'Name des Journals',
    'Place/City' => 'Erscheinungsort',
    'Publisher' => 'Verlagsanstalt',
    'Volume' => 'Band',
    'Issue' => 'Ausgabe',
    'Pages' => 'Seiten',
    'Start Page' => 'Erste Seite',
    'ISSN' => 'ISSN',
    'Series' => 'Publikationsreihe',
    'Series Editor' => 'Herausgeber der Buchreihe',
    'Series Title' => 'Titel der Buchreihe',
    'Series Book Editor' => 'Herausgeber der Reihe',
    'Series Book Title' => 'Titel der Reihe',

    'Series Volume' => 'Band der Buchreihe',
    'Number of pages' => 'Seitenzahl',
    'Editor' => 'Herausgeber',
    'Edition' => 'Ausgabe/Auflage',
    'ISBN' => 'ISBN',


    // Test Tooltips
    '1-isbn-help'    => 'Verwenden sie keine Bindestriche; die ISBN wird automatisch formatiert.',
    '7-authors-help' => 'Nachname, Vorname. Vornamen ungekürzt. Autoren in eine neue Zeile. Ist der Autor eine Organisation, schließe den Autorennamen mit einem Komma ab.',
];
